services:
  app:
    build:
      context: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "until [ -f vendor/autoload.php ]; do
      echo 'Waiting for composer install...'; sleep 2;
      done; php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  node:
    image: node:22-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "if [ ! -d node_modules/vue ]; then npm install; fi &&
      npm run dev -- --host 0.0.0.0"

volumes:
  mysql_data:
  node_modules:
